2024-09-17 19:37:42,115 DEBUG    root            Loaded Command Group: ['gcloud', 'iam']
2024-09-17 19:37:42,118 DEBUG    root            Loaded Command Group: ['gcloud', 'iam', 'service_accounts']
2024-09-17 19:37:42,228 DEBUG    root            Loaded Command Group: ['gcloud', 'iam', 'service-accounts', 'add_iam_policy_binding']
2024-09-17 19:37:42,268 DEBUG    root            Running [gcloud.iam.service-accounts.add-iam-policy-binding] with arguments: [--member: "serviceAccount:836062129100@cloudbuild.gserviceaccount.com", --role: "roles/iam.serviceAccountUser", SERVICE_ACCOUNT: "socialai-432601@appspot.gserviceaccount.com"]
2024-09-17 19:37:42,344 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): iam.googleapis.com:443
2024-09-17 19:37:42,614 DEBUG    urllib3.connectionpool https://iam.googleapis.com:443 "POST /v1/projects/socialai-432601/serviceAccounts/socialai-432601@appspot.gserviceaccount.com:getIamPolicy?alt=json&options.requestedPolicyVersion=3 HTTP/1.1" 200 None
2024-09-17 19:37:42,654 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): iam.googleapis.com:443
2024-09-17 19:37:42,940 DEBUG    urllib3.connectionpool https://iam.googleapis.com:443 "POST /v1/projects/socialai-432601/serviceAccounts/socialai-432601@appspot.gserviceaccount.com:setIamPolicy?alt=json HTTP/1.1" 403 None
2024-09-17 19:37:42,947 DEBUG    root            Chosen display Format:default
2024-09-17 19:37:42,983 DEBUG    root            Chosen display Format:default
2024-09-17 19:37:42,986 DEBUG    root            Chosen display Format:default
2024-09-17 19:37:42,987 DEBUG    root            (gcloud.iam.service-accounts.add-iam-policy-binding) PERMISSION_DENIED: Permission 'iam.serviceAccounts.setIamPolicy' denied on resource (or it may not exist). This command is authenticated as 836062129100-compute@developer.gserviceaccount.com which is the active account specified by the [core/account] property.
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: iam.googleapis.com
  metadata:
    permission: iam.serviceAccounts.setIamPolicy
  reason: IAM_PERMISSION_DENIED
Traceback (most recent call last):
  File "/snap/google-cloud-cli/269/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/269/lib/googlecloudsdk/calliope/backend.py", line 838, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/269/lib/googlecloudsdk/command_lib/util/apis/yaml_command_translator.py", line 1373, in Run
    ref, response = self._CommonRun(args)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/269/lib/googlecloudsdk/command_lib/util/apis/yaml_command_translator.py", line 455, in _CommonRun
    response = method.Call(
               ^^^^^^^^^^^^
  File "/snap/google-cloud-cli/269/lib/googlecloudsdk/command_lib/util/apis/registry.py", line 341, in Call
    return request_func(global_params=global_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/269/lib/googlecloudsdk/command_lib/util/apis/registry.py", line 404, in RequestFunc
    return method(request, global_params=global_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/269/lib/googlecloudsdk/generated_clients/apis/iam/v1/iam_v1_client.py", line 4217, in SetIamPolicy
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/269/lib/third_party/apitools/base/py/base_api.py", line 737, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/269/lib/third_party/apitools/base/py/base_api.py", line 743, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/269/lib/third_party/apitools/base/py/base_api.py", line 609, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://iam.googleapis.com/v1/projects/socialai-432601/serviceAccounts/socialai-432601@appspot.gserviceaccount.com:setIamPolicy?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Tue, 17 Sep 2024 19:37:42 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': 403}>, content <{
  "error": {
    "code": 403,
    "message": "Permission 'iam.serviceAccounts.setIamPolicy' denied on resource (or it may not exist).",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "IAM_PERMISSION_DENIED",
        "domain": "iam.googleapis.com",
        "metadata": {
          "permission": "iam.serviceAccounts.setIamPolicy"
        }
      }
    ]
  }
}
>
2024-09-17 19:37:42,992 ERROR    root            (gcloud.iam.service-accounts.add-iam-policy-binding) PERMISSION_DENIED: Permission 'iam.serviceAccounts.setIamPolicy' denied on resource (or it may not exist). This command is authenticated as 836062129100-compute@developer.gserviceaccount.com which is the active account specified by the [core/account] property.
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: iam.googleapis.com
  metadata:
    permission: iam.serviceAccounts.setIamPolicy
  reason: IAM_PERMISSION_DENIED
